apiVersion: 1

datasources:
  - name: CSV Local
    type: yesoreyeram-infinity-datasource
    uid: csv-local
    access: proxy
    url: http://csv-server
    isDefault: true
    jsonData:
      global_queries: []
    version: 1
    editable: true
